config/routes.rb
Rails.application.routes.draw do

  root 'shoutouts#index'

  post '/shoutout' => 'shoutouts#create'
  post '/cheer' => 'cheers#create'

  get '/users/location_missing' => 'users#location_missing'
  post '/users/set_location' => 'users#set_location'

  get '/tag/:tag' => 'shoutouts#tag'
  get '/reveal' => 'shoutouts#reveal'
  get '/reveal/:tag' => 'shoutouts#reveal'
  get 'help' => 'static#help'

  namespace :admin do
    root 'home#index'
    resources :metrics, only: :index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def cheer
    latest = Cheer.latest_for_user(params[:user_name])

    if params[:text].strip == 'undo'
      latest.last.delete unless latest.empty?
      return render text: 'Cheer undone!'
    elsif params[:text].strip == 'clear'
      latest.delete_all
      return render text: 'Cheers cleared!'
    end

    names = []
    params[:text].scan(/#[0-9]+/).each do |id|
      latest.limit(1).first.delete if latest.size >= 3
      next unless (shoutout = Shoutout.find_by_id(id[1..-1]))
      if shoutout.recipients.include?(params[:user_name])
        return render text: 'Cheeky! There are other ways to rig this election!'
      end
      Cheer.create(sender: params[:user_name], shoutout: shoutout)
      names << shoutout.recipients
    end
    if names.empty?
      render text: "Woah there, how about making some valid cheers next time?"
    else
      render text: "Hip Hip! You cheered for #{names.uniq.join(' & ')}!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand title" href="/">Three Cheers</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Help & How To', help_path %></li>
        <li><a href="https://trello.com/b/lTJyK69o/cheers">Feedback <i class="glyphicon glyphicon-new-window"></i></a></li>
        <li class="active"><%= link_to 'London', '/tag/london' %></li>
        <li class="active"><%= link_to 'Cape Town', '/tag/capetown' %></li>
        <%= content_tag 'li' do %>
           <%= link_to 'Metrics', admin_metrics_path %>
        <% end if admin_view %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <p class="navbar-text"><%= render 'shoutouts/summary', shoutouts: shoutouts %></p>
        </li>
      </ul>
    </div>
  </div>
</nav>